In [1]:

# Importando as dependências
from sklearn.neural_network import MLPClassifier
import numpy as np
import pandas as pd
import matplotlib.pyplot as mpl
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

In [2]:

#Importando dataset
df = pd.read_csv('dados/multiplelinearregretion.csv', delimiter=',')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df.rename(columns={'R&D Spend':'RDSpende', 'Marketing Spend': 'MarketingSpend'}, inplace=True)
df.head()

RDSpende  Administration  MarketingSpend       State     Profit
0  165349.20       136897.80       471784.10    New York  192261.83
1  162597.70       151377.59       443898.53  California  191792.06
2  153441.51       101145.55       407934.54     Florida  191050.39
3  144372.41       118671.85       383199.62    New York  182901.99
4  142107.34        91391.77       366168.42     Florida  166187.94

In [4]:
df.corr()

RDSpende  Administration  MarketingSpend    Profit
RDSpende        1.000000        0.241955        0.724248  0.972900
Administration  0.241955        1.000000       -0.032154  0.200717
MarketingSpend  0.724248       -0.032154        1.000000  0.747766
Profit          0.972900        0.200717        0.747766  1.000000

In [5]:
# Preparando os dados
X = df.iloc[:, :-1].values # Todas as dimensões, exceto a Profit
y = df.iloc[:, -1].values

In [6]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [7]:
labelEnconding = LabelEncoder()
X[:, -1] = labelEnconding.fit_transform(X[:, -1])

X[:, -1]

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0], dtype=object)

In [8]:
ohe = OneHotEncoder(categorical_features=[3]) # 
# X = ohe.fit_transform(X).toarray() # Realizando a criação das Dummy Variables
# X

# y = ohe.fit_transform(y).toarray()
# y

# # Aplicando a técnica Dummy Coding
dc = OneHotEncoder(handle_unknown='ignore')
# # Realizando treinamento
# y = dc.fit_transform(y.reshape(-1, 1)).toarray()
X = dc.fit_transform(X.reshape(-1, 1)).toarray()

# y

In [9]:
# X = X[:, 1:]
# y
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [10]:
# Seleção de amostras para treino e teste
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3)

ValueError: Found input variables with inconsistent numbers of samples: [200, 50]

In [ ]:
# Criando um modelo de Rede Neural MLP
classificador = MLPClassifier(hidden_layer_sizes=(2,), activation='logistic', solver='adam', verbose=10, random_state=1,
                    learning_rate_init=.01,  max_iter=1000);




In [ ]:
# Treinando o modelo
classificador.fit(X_treino, y_treino)
# y_treino

In [ ]:
# classificador.predict(X_teste)
# print(classificador.predict(X_teste))
classificador.score(X_teste, y_teste)